### ISSUE TITLE
ES module tips

### ISSUE THREAD

**Issue by J-env** [ungap/custom-elements#16]
@ungap/custom-elements doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/25259920/205322516-5a331a11-0c84-42a7-93f9-6d2feba93495.png">

**Comment by WebReflection** [comment]
it's a polyfill ... it doesn't matter at all what kind of CommonJS or ESM module it is, you import or require it without needing to assign it to anything, as it doesn't export anything at all.

```js
// you're done in ESM
import '@ungap/custom-elements';

// you're done in CommonJS
require('@ungap/custom-elements');
```

please file a bug in **Astro** as there's nothing I need to do here, 'cause that's how side-effecting on the global polyfills work, thanks.
