### ISSUE TITLE
Error on Safari 9: Attemped to assign to readonly property

### ISSUE THREAD

**Issue by 007lva** [ungap/custom-elements#2]
First, thanks a lot for your work on this polyfill, it works quite well for us at [rankia.com](www.rankia.com/). I've just found a bug on Safari 9 that maybe you will be interested to check since the README mentions that even Safari 8 is supported:

![Screenshot_2020-11-23_20-56-34](https://user-images.githubusercontent.com/1860816/100009010-87376700-2dce-11eb-96ff-76cc4dd90649.png)

If you need to reproduce it, just visit the home page of rankia.com, Safari > 10 doesn't show any error.

**Comment by WebReflection** [comment]
I'm glad this module works for you but I've no idea what you expect me to do with a minified file that fails at column 2974 on line 2.

Closing until further details are provided on what doesn't work exactly.

**Comment by WebReflection** [comment]
To clarify further, this issue scores 3 out of 5 **don't** points, when it comes to file a bug, so please have a read and help me helping you
https://gist.github.com/WebReflection/f6dc8017a1c10f0ece2e292b0b9607ff

**Comment by 007lva** [comment]
I see, now I've tried the full version get more details and this is the line which is throwing the exception:

https://github.com/ungap/custom-elements/blob/master/index.js#L268
> (HTMLBuiltIn.prototype = HTMLElement.prototype).constructor = HTMLBuiltIn;

`TypeError: Attemped to assign to readonly property`

I've found this error on Safari 9.1 on OS X El Capitan (through Browserstack). Do you need more details? Thanks!

**Comment by WebReflection** [comment]
That's way better, thanks. As I couldn't find the issue in an entire **minute** browserstack gave me, I'm downloading EL Captain image and I will run more tests in VB. That list of browsers though was copied from the older polyfill, which did work on Safari 8 too, but it looks like Safari <= 9 has a non writable constructor, I need to check if it's at least configurable.

Meanwhile, if super-legacy is needed, you can copy and paste this `<script>` instead, on top of your files (the `\x2f` is *not* a typo, it's exactly how it should be)

```html
<script>
if(!self.customElements)document.write('<script src="https://unpkg.com/document-register-element"><\x2fscript>');
</script>
<script src="https://unpkg.com/@ungap/custom-elements"></script>
```
note that the order matters, so just literally copy and paste this on *top* of your `<head>` tag and you're good to go, eventually use `<script defer>` for the *ungap* script **only**, and don't worry/care about the `document.write` as no modern browser will ever use it.

**Comment by WebReflection** [comment]
P.S. alternatively, to avoid double patch on builtin extends, you can try this instead:

```html
<script>
(function(w,d,p,h){
h=d.documentElement;
h.insertBefore(
  d.createElement('script'),
  h.firstChild
).src=p+(w.customElements?'@ungap/custom-elements':'document-register-element');
}(this,document,'https://unpkg.com/'));
</script>
```

**Comment by WebReflection** [comment]
as installing El Captain in Virtual Box is everything but trivial, I wonder if you could tell me what the console shows when typing this:

```js
Object.getOwnPropertyDescriptor(HTMLElement.prototype, 'constructor');
```

`writable`, `configurable`, and all properties are the one I am after, thanks.

**Comment by 007lva** [comment]
Here you have:

![Screenshot_2020-11-27_11-11-35](https://user-images.githubusercontent.com/1860816/100437699-6eb29f80-30a1-11eb-8cc9-f17c870342db.png)

**Comment by WebReflection** [comment]
awesome!

**Comment by WebReflection** [comment]
This should be fixed now, please let me know if that's not the case (also please wait until unpkg catches up with the latest version) 👋

**Comment by 007lva** [comment]
Thanks! Now it works even on Safari 8.
