### ISSUE TITLE
setAttribute problem in IE11

### ISSUE THREAD

**Issue by grofzero** [ungap/custom-elements#3]
Hi,

I'm using Vue, and I changed to this lib from document-register-element, but when I use a webcomponent inside Vue component, it breaks on this line: node.setAttribute(scopeId, '')

Could You take a look at this problem?

Thanks in advance,
grofzero

**Comment by WebReflection** [comment]
which problem? I have literally nothing to work on with the info you gave me ... IE11 is tested and working here:
https://webreflection.github.io/custom-elements/test/

**Comment by WebReflection** [comment]
closing, as no extra info has been provided in more than a year.
