### ISSUE TITLE
After adding @ungap/custom-elements as polyfill to Angular project throws error

### ISSUE THREAD

**Issue by aliuspetraska** [ungap/custom-elements#4]
Hi,

After adding `@ungap/custom-elements` (latest) as polyfill to Angular (latest) project, after build it throws an error on Safari (latest): `SyntaxError: The string did not match the expected pattern.`.

**Comment by WebReflection** [comment]
how am I supposed to help in here? I've no idea what you are doing, I've no idea how to reproduce anything, so I'm closing this issue as it's very badly written.

https://gist.github.com/WebReflection/f6dc8017a1c10f0ece2e292b0b9607ff
